In [1]:
import scipy.signal
import numpy as np

### Same-sized arrays

In [2]:
v1 = np.asarray([1,2,3])
v2 = np.asarray([1,2,3])
scipy.signal.correlate(v1,v2)

array([ 3,  8, 14,  8,  3])

In [3]:
scipy.signal.correlate(v1,v2,mode="same")

array([ 8, 14,  8])

In [4]:
scipy.signal.correlate(v1,v2,mode="valid")

array([14])

In [5]:
np.dot(v1,v2)

14

### Different-sized arrays

In [6]:
v3 = np.asarray([1,2,3,4,5,6])
v4 = np.asarray([5,6])
scipy.signal.correlate(v3,v4,mode="full")

array([ 6, 17, 28, 39, 50, 61, 30])

In [7]:
scipy.signal.correlate(v3,v4,mode="same")

array([ 6, 17, 28, 39, 50, 61])

In [8]:
scipy.signal.correlate(v3,v4,mode="valid")

array([17, 28, 39, 50, 61])